2022-09-30 21:01:26,910 ERROR Internal Server Error: /newss/ C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\utils\log.py (exc_info) log.py
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\template\loader_tags.py", line 226, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
2022-09-30 21:01:26,920 ERROR "GET /newss/ HTTP/1.1" 500 183047 C:\Users\Acer\AppData\Local\Programs\Python\Python38\lib\site-packages\django\core\servers\basehttp.py (exc_info) basehttp.py
